
-- =============================================
-- Author:		Mark Richman
-- Create date: 10/23/2013
-- Description:	EmailVision Order Confirmation
-- Example:     exec EmailVision_GetOrderById 865271
-- =============================================
ALTER PROCEDURE [dbo].[EmailVision_GetOrderById]
	@id as integer
AS
BEGIN

SELECT DISTINCT
	CMS.ORDERNO, CMS.CUSTNUM, CUST.FIRSTNAME, CUST.LASTNAME, CUST.EMAIL, ITEMS.ITEM, ITEMS.ITEM_STATE,
	CAST(ITEMS.QUANTO AS INT) AS QUANTO, ItemInfo.DESC1,
	ISNULL(ITEMS.SHIP_WHEN, DATEADD(d, 1, GETDATE())) AS NEXT_SHIP,
	((ITEMS.IT_UNLIST) - ((ITEMS.IT_UNLIST) * (ITEMS.DISCOUNT / 100))) AS IT_UNLIST,
	CMS.TAX, CMS.SHIPPING, CMS.ORD_TOTAL,
	'' AS SourceKey, CMS.ODR_DATE, CUST.ADDR, CUST.ADDR2, CUST.CITY, CUST.STATE,
	CUST.ZIPCODE, CMS.CARDTYPE, ITEMS.DISCOUNT,
	ISNULL(CUST_SHIP.ADDR, CUST.ADDR) AS SHIP_ADDR,
	ISNULL(CUST_SHIP.ADDR2, CUST.ADDR2) AS SHIP_ADDR2,
	ISNULL(CUST_SHIP.CITY, CUST.CITY) AS SHIP_CITY,
	ISNULL(CUST_SHIP.STATE, CUST.STATE) AS SHIP_STATE,
	ISNULL(CUST_SHIP.ZIPCODE, CUST.ZIPCODE) AS SHIP_ZIPCODE
FROM CMS (NOLOCK)
	INNER JOIN ITEMS (NOLOCK) ON CMS.ORDERNO = ITEMS.ORDERNO
	INNER JOIN CUST (NOLOCK) ON CMS.CUSTNUM = CUST.CUSTNUM
	INNER JOIN (SELECT DISTINCT NUMBER, DESC1 FROM STOCK (NOLOCK)) AS ItemInfo ON ITEMS.ITEM = ItemInfo.NUMBER
	LEFT OUTER JOIN CUSTRELA (NOLOCK) ON (CMS.CUSTNUM = CUSTRELA.CUSTNUM)
	LEFT OUTER JOIN CUST AS CUST_SHIP (NOLOCK) ON (CUSTRELA.BELONGNUM = CUST_SHIP.CUSTNUM AND CUSTRELA.RELA_TYPE='S')
WHERE 1=1
	AND CMS.ORDERNO = @id
	AND (ITEMS.IT_UNCOST > 0)
	AND ((ITEMS.NONPRODUCT = 0) OR (ITEMS.IT_UNLIST <> 0))
	AND (CUST.EMAIL <> '')
	AND NOT (CMS.ORDERNO IN (SELECT LAST_ORDER FROM CLUBSUBS (NOLOCK)))

END

