
-- =============================================
-- Author:		Mark Richman
-- Create date: 9/10/2013
-- Description:	EmailVision Order Confirmation
-- Example:     exec EmailVision_GetNewOrders
-- =============================================
ALTER PROCEDURE [dbo].[EmailVision_GetNewOrders]
	-- Add the parameters for the stored procedure here

AS
BEGIN
SELECT
	CMS.ORDERNO, CMS.CUSTNUM, CUST.FIRSTNAME, CUST.LASTNAME, CUST.EMAIL, ITEMS.ITEM,
	CAST(ITEMS.QUANTO AS INT) AS QUANTO, ItemInfo.DESC1,
	ItemInfo.DESC2, ISNULL(ITEMS.SHIP_WHEN, DATEADD(d, 1, GETDATE())) AS NEXT_SHIP,
	((ITEMS.IT_UNLIST) - ((ITEMS.IT_UNLIST) * (ITEMS.DISCOUNT / 100))) AS IT_UNLIST,
	CMS.TAX, CMS.SHIPPING, CMS.ORD_TOTAL,
	'' AS SourceKey, CMS.ODR_DATE, CUST.ADDR, CUST.ADDR2, CUST.CITY, CUST.STATE,
	CUST.ZIPCODE, CMS.CARDTYPE, ITEMS.DISCOUNT,
	ISNULL(CUST_SHIP.ADDR, CUST.ADDR) AS SHIP_ADDR,
	ISNULL(CUST_SHIP.ADDR2, CUST.ADDR2) AS SHIP_ADDR2,
	ISNULL(CUST_SHIP.CITY, CUST.CITY) AS SHIP_CITY,
	ISNULL(CUST_SHIP.STATE, CUST.STATE) AS SHIP_STATE,
	ISNULL(CUST_SHIP.ZIPCODE, CUST.ZIPCODE) AS SHIP_ZIPCODE
FROM CMS (NOLOCK)
	INNER JOIN ITEMS (NOLOCK) ON CMS.ORDERNO = ITEMS.ORDERNO
	INNER JOIN CUST (NOLOCK) ON CMS.CUSTNUM = CUST.CUSTNUM
	INNER JOIN (SELECT DISTINCT NUMBER, DESC1, DESC2
		FROM STOCK (NOLOCK)) AS ItemInfo ON ITEMS.ITEM = ItemInfo.NUMBER
	LEFT OUTER JOIN CUSTRELA (NOLOCK) ON (CMS.CUSTNUM = CUSTRELA.CUSTNUM)
	LEFT OUTER JOIN CUST AS CUST_SHIP (NOLOCK) ON (CUSTRELA.BELONGNUM = CUST_SHIP.CUSTNUM AND CUSTRELA.RELA_TYPE='S')
WHERE 1=1 -- CUST.NOEMAIL = 0
	AND (CMS.ODR_DATE BETWEEN DATEADD(d, -1, GETDATE()) AND GETDATE())
	AND (ITEMS.IT_UNCOST > 0)
	AND ((ITEMS.NONPRODUCT = 0) OR (ITEMS.IT_UNLIST <> 0))
	AND (CUST.EMAIL <> '')
	AND NOT (CMS.ORDERNO IN (SELECT LAST_ORDER FROM CLUBSUBS (NOLOCK)))
	-- AND (PROCSSD = 0)
	AND NOT (CUST.EMAIL LIKE '%amazon.com')
	--AND
	--  ((SELECT     COUNT(CUSTNUM) AS Expr1
	--	  FROM         CONTACT (NOLOCK)
	--	  WHERE     (CUSTNUM = CUST.CUSTNUM) AND (ORDNUM = CMS.ORDERNO)) = 0)
	AND ((ITEMS.ITEM_STATE = 'CM') OR (ITEMS.ITEM_STATE = 'BO'))
	AND NOT (CUST.CUSTNUM IN (SELECT DISTINCT CUSTNUM FROM CMS WHERE CL_KEY = 'AMAZON'))
--	UNION
--	SELECT   1745637, 'Mark', 'Richman', 'mark.richman@nutrihealth.com', 777, '10503', 3, 'AtrhroZyme Plus', 'Atrhrozyme Plus is cool', DATEADD(DD, 1, GETDATE()), 15 AS IT_UNLIST, 0, 3.95, 18.95,
--					'' AS SourceKey
	ORDER BY CMS.ORDERNO, ITEMS.QUANTO DESC, ITEMS.IT_UNLIST DESC


END

