
-- =============================================
-- Author:		Mark Richman
-- Create date: 9/12/2013
-- Description:	Gets Backorders for EmailVision
-- =============================================
ALTER PROCEDURE [dbo].[EmailVision_GetBackOrders]
	-- Add the parameters for the stored procedure here
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		CMS.ORDERNO,
		CMS.CUSTNUM,
		CUST.FIRSTNAME,
		CUST.LASTNAME,
		CUST.EMAIL,
		ITEMS.ITEM,
		CAST(ITEMS.QUANTO AS INT) AS QUANTO,
		ItemInfo.DESC1,
		ItemInfo.DESC2,
		ISNULL(ITEMS.SHIP_WHEN, DATEADD(d, 1, GETDATE())) AS NEXT_SHIP,
		((ITEMS.IT_UNLIST) - ((ITEMS.IT_UNLIST) * (ITEMS.DISCOUNT / 100))) AS IT_UNLIST,
		CMS.TAX,
		CMS.SHIPPING,
		CMS.ORD_TOTAL,
		ITEMS.ITEM_STATE,
		'BONOTICE' AS SourceKey
	FROM
		CMS WITH (NOLOCK)
		INNER JOIN ITEMS WITH (NOLOCK) ON CMS.ORDERNO = ITEMS.ORDERNO
		INNER JOIN CUST WITH (NOLOCK) ON CMS.CUSTNUM = CUST.CUSTNUM
		INNER JOIN (SELECT DISTINCT NUMBER, DESC1, DESC2
					FROM STOCK WITH (NOLOCK)) AS ItemInfo ON ITEMS.ITEM = ItemInfo.NUMBER
	WHERE 1=1
		--(CUST.NOEMAIL = 0)
		--AND (CMS.ODR_DATE BETWEEN DATEADD(d, - 1, GETDATE()) AND GETDATE())
		--AND (ITEMS.ITEM = @SKU)
		AND (CUST.EMAIL <> '')
		AND NOT (CUST.EMAIL LIKE '%amazon.com')
		--AND	((SELECT COUNT(CUSTNUM) AS Expr1
		--		FROM   CONTACT WITH (NOLOCK)
		--		WHERE  (CUSTNUM = CUST.CUSTNUM) AND (ORDNUM = CMS.ORDERNO) --AND (CONTACT_ID = 0)
		--	    AND (LETCODE = 'BONot')) = 0)
		AND (ITEMS.ITEM_STATE = 'BO')
	ORDER BY CMS.ORDERNO, ITEMS.ITEM, ITEMS.ITEM_STATE


END

